import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion,useScroll,useSpring} from 'framer-motion';
import './styles.css';


function ImageWithFallback({src,alt,className}){
 const [failed,setFailed]=useState(false);
 if(failed) return <div className={(className||'')+' imageFallback'}><span>{alt}</span></div>;
 return <img src={src} alt={alt} className={className} onError={()=>setFailed(true)}/>;
}

function Icon({name,size=16}){
 const p={
  ArrowDown:<path d="M12 5v14m0 0 5-5m-5 5-5-5"/>,
  ArrowUpRight:<><path d="M7 17 17 7"/><path d="M7 7h10v10"/></>,
  Download:<><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></>,
  Github:<><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7A5.5 5.5 0 0 0 19.3 4 5.1 5.1 0 0 0 19.2 1S18 0.6 15 2.6a13.4 13.4 0 0 0-6 0C6 0.6 4.8 1 4.8 1a5.1 5.1 0 0 0-.1 3A5.5 5.5 0 0 0 3.2 7.5c0 5.4 3.5 6.6 6.8 7A4.8 4.8 0 0 0 9 18v4"/><path d="M9 18c-4.5 2-5-2-7-2"/></>,
  Linkedin:<><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4v-13h4v2"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></>,
  Mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>,
  Menu:<><path d="M4 7h16"/><path d="M4 12h16"/><path d="M4 17h16"/></>,
  X:<><path d="M6 6l12 12"/><path d="M18 6 6 18"/></>
 };
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>
}

const projects=[
['Nova Digital Studio','Digital Agency','01_Nova_Digital_Studio.png','A premium digital agency experience with an animated hero, custom cursor effects, project showcase and interactive UI components designed for desktop and mobile.',['Animated hero','Custom cursor','Scroll reveals','Animated counters']],
['LearnSphere LMS','Learning Platform','02_LearnSphere_LMS.png','A responsive learning-management dashboard with course progress tracking, activity charts, certificates, live search and category filters.',['Progress tracking','Activity charts','Live search','Dashboard interactions']],
['Volt Performance','Fitness Platform','03_Volt_Performance.png','A premium fitness platform featuring an animated hero, training programs, coach profiles, performance metrics, recovery content and membership pricing.',['Animated statistics','Data visualization','Coach profiles','Responsive UI']],
['Nexora AI','AI Product','nexora-ai-premium-project-5.png','A polished AI-focused product interface built around a modern visual system, clear content hierarchy and engaging interactions.',['Modern product UI','Interactive sections','Responsive layout','Visual storytelling']],
['Noir & Olive','Premium Brand','noir-olive-premium-project-2-v2.png','A sophisticated brand website concept focused on premium typography, editorial composition, elegant spacing and a refined visual identity.',['Editorial layout','Premium typography','Hover effects','Responsive design']],
['Aurelia Luxury Travel','Travel Experience','aurelia-luxury-travel-project-3.png','A luxury travel experience designed to combine immersive imagery, elegant presentation and responsive interactions across screen sizes.',['Immersive hero','Destination presentation','Smooth interactions','Mobile friendly']],
['Veloura Fashion','Fashion Experience','veloura-premium-fashion-project-4.png','A fashion-forward interface built with a premium visual language, product storytelling, responsive layouts and polished interaction details.',['Fashion UI','Product storytelling','Responsive cards','Micro-interactions']],
['Luxury Store','E-Commerce','luxury-store-project-1.png','A modern luxury-store concept with strong product presentation, promotional sections, responsive navigation and interactive interface elements.',['Product presentation','Promotional sections','Responsive navigation','Interactive UI']]
];
const links={github:'https://github.com/abdulsalam72907-bit',linkedin:'https://www.linkedin.com/in/abdul-salam-mahar-b894b4414',email:'mailto:Abdulsalam72907@gmail.com'};
const ease=[.22,1,.36,1];
const reveal={hidden:{opacity:0,y:30},visible:{opacity:1,y:0,transition:{duration:.7,ease}}};

function App(){const [menu,setMenu]=useState(false),[active,setActive]=useState(null);const {scrollYProgress}=useScroll();const bar=useSpring(scrollYProgress,{stiffness:100,damping:30});useEffect(()=>{document.body.style.overflow=active?'hidden':'';return()=>document.body.style.overflow=''},[active]);
return <><motion.div className="progress" style={{scaleX:bar}}/><div className="noise"/>
<header className="nav"><a className="brand" href="#top"><b>AS</b><span>ABDUL SALAM</span></a><div className="links">{['about','skills','work','experience','contact'].map(x=><a key={x} href={'#'+x}>{x}</a>)}</div><div className="actions"><a className="cv" href="/Abdul-Salam-CV.docx" download>CV <Icon name="Download" size={13}/></a><a href={links.github} target="_blank">GitHub</a><a href={links.linkedin} target="_blank">LinkedIn</a><a className="email" href={links.email}>Email me <Icon name="ArrowUpRight" size={14}/></a></div><button className="menubtn" onClick={()=>setMenu(!menu)}>{menu?<Icon name="X"/>:<Icon name="Menu"/>}</button></header>
<AnimatePresence>{menu&&<motion.div className="mobile" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{['about','skills','work','experience','contact'].map(x=><a key={x} href={'#'+x} onClick={()=>setMenu(false)}>{x}</a>)}<a href="/Abdul-Salam-CV.docx" download>Download CV ↓</a><a href={links.github} target="_blank">GitHub ↗</a><a href={links.linkedin} target="_blank">LinkedIn ↗</a></motion.div>}</AnimatePresence>
<div className="topstrip"><div><span>LET'S CONNECT</span><a href={links.email}>Abdulsalam72907@gmail.com</a><a href={links.github} target="_blank">GitHub ↗</a><a href={links.linkedin} target="_blank">LinkedIn ↗</a><a className="green" href="/Abdul-Salam-CV.docx" download>Download CV ↓</a></div></div>
<main id="top"><section className="section hero"><div className="grid"/><motion.div className="heroText" initial="hidden" animate="visible" variants={reveal}><small className="eyebrow"><i/> AVAILABLE FOR FRONTEND OPPORTUNITIES</small><h1>I build <em>digital experiences</em> that feel as good as they look.</h1><p>Frontend Web Developer focused on responsive interfaces, thoughtful UI/UX, clean code and motion that has a purpose.</p><div className="heroBtns"><a className="btn primary" href="#work">Explore my work <Icon name="ArrowDown" size={16}/></a><a className="btn" href="#contact">Get in touch <Icon name="ArrowUpRight" size={16}/></a><a className="btn cvbtn" href="/Abdul-Salam-CV.docx" download>Download CV <Icon name="Download" size={16}/></a></div><div className="socials"><a href={links.github} target="_blank"><Icon name="Github" size={14}/> GitHub</a><a href={links.linkedin} target="_blank"><Icon name="Linkedin" size={14}/> LinkedIn</a><a href={links.email}><Icon name="Mail" size={14}/> Email</a></div><div className="meta">Lahore, Pakistan <i/> BS Computer Science · UMT</div></motion.div><motion.div className="visual" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:1}}><div className="halo a"/><div className="halo b"/><div className="portrait"><ImageWithFallback src="/images/abdul-salam.jpg" alt="Abdul Salam"/><div className="caption"><span>FRONTEND</span><b>WEB DEVELOPER</b></div></div><motion.div className="float one" animate={{y:[0,-12,0]}} transition={{duration:5,repeat:Infinity}}><b>8+</b><small>Selected<br/>projects</small></motion.div><motion.div className="float two" animate={{y:[0,10,0]}} transition={{duration:5,repeat:Infinity,delay:1}}><b>UI</b><small>Detail<br/>driven</small></motion.div></motion.div></section>
<div className="marquee"><div>{['HTML5','✦','CSS3','✦','JAVASCRIPT','✦','BOOTSTRAP','✦','TAILWIND CSS','✦','UI / UX','✦','HTML5','✦','CSS3','✦','JAVASCRIPT','✦','BOOTSTRAP','✦','TAILWIND CSS','✦','UI / UX','✦'].map((x,i)=><span key={i} className={x==='✦'?'star':''}>{x}</span>)}</div></div>
<Section id="about" n="01 / About"><div className="about"><motion.h2 variants={reveal}>Designing with <span>clarity.</span><br/>Building with <span>purpose.</span></motion.h2><motion.div variants={reveal}><p className="lead">I'm Abdul Salam, a Frontend Web Developer who enjoys turning ideas into responsive, interactive and visually polished web interfaces.</p><p>My work combines modern layout systems, UI principles, animations and practical JavaScript interactions. I care about spacing, typography, responsiveness, hierarchy and smooth interaction.</p><div className="signature">AS<span>—</span></div></motion.div></div><div className="stats">{[['8','Selected projects'],['5','Core frontend skills'],['1','Professional experience'],['4','Semester · BS CS']].map(x=><motion.div variants={reveal} className="stat" key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></motion.div>)}</div></Section>
<Section id="skills" n="02 / Capabilities"><Head title={<>Tools I use to turn<br/><span>ideas into interfaces.</span></>} text="Focused on frontend craftsmanship, responsive systems and polished interaction."/><div className="skills">{[['01','Frontend Development','Semantic HTML, modern CSS and JavaScript for responsive, interactive experiences.',['HTML','CSS','JavaScript']],['02','UI / UX Principles','Clear hierarchy, visual rhythm, accessible interactions and user-focused layouts.',['Layout','Typography','Interaction']],['03','Responsive Design','Interfaces designed to feel consistent across desktop, tablet and mobile devices.',['Mobile','Tablet','Desktop']],['04','Development Workflow','Comfortable with tools that support a clean, practical development workflow.',['VS Code','Git','GitHub','DevTools']],['05','CSS Frameworks','Building faster and cleaner layouts with established responsive frameworks.',['Bootstrap','Tailwind CSS']],['06','Core Python + OOP','Foundational Python programming with an object-oriented approach to problem solving.',['Python','OOP']]].map(s=><motion.article variants={reveal} whileHover={{y:-6}} className="skill" key={s[0]}><small>{s[0]}</small><h3>{s[1]}</h3><p>{s[2]}</p><div>{s[3].map(t=><i key={t}>{t}</i>)}</div></motion.article>)}</div></Section>
<Section id="work" n="03 / Selected work"><Head title={<>A few things<br/><span>I've built.</span></>} text="Project previews and short case-study notes. No external project links are included here."/><div className="projects">{projects.map((p,i)=><motion.article variants={reveal} className="project" key={p[0]}><button onClick={()=>setActive(p)} className="projectImg"><ImageWithFallback src={'/images/projects/'+p[2]} alt={p[0]+' screenshot'}/><span>View case study</span></button><div><small>0{i+1} / {p[1]}</small><h3>{p[0]}</h3><p>{p[3]}</p><div className="tags">{p[4].map(t=><i key={t}>{t}</i>)}</div><label>HTML · CSS · JavaScript</label></div></motion.article>)}</div></Section>
<Section id="experience" n="04 / Experience"><div className="experience"><motion.h2 variants={reveal}>Learning, building,<br/><span>and growing.</span></motion.h2><div className="timeline">{[['JUL 2026 — AUG 2026','Frontend Developer','Hi Tech Software Development','Built and maintained responsive front-end interfaces using HTML, CSS, Bootstrap, Tailwind CSS and JavaScript. Collaborated with the development team to implement UI components and improve website performance.'],['CURRENT','BS Computer Science','UMT Lahore · 4th Semester','Continuing academic development across computer science fundamentals while building practical frontend projects and strengthening software development skills.'],['CERTIFICATE','Frontend Web Developer','PNY Trainings · Arfa Tower, Lahore','Professional frontend training focused on modern web development, responsive design and practical interface building.'],['CERTIFICATE','Core Python with OOP','PNY Trainings · Arfa Tower, Lahore','Core Python and object-oriented programming foundations used to strengthen programming logic and structured problem solving.']].map(x=><motion.article variants={reveal} key={x[1]}><i/><div><small>{x[0]}</small><h3>{x[1]}</h3><b>{x[2]}</b><p>{x[3]}</p></div></motion.article>)}</div></div></Section>
<Section id="contact" n="05 / Contact"><motion.div className="contact" variants={reveal}><h2>Have an idea?<br/><span>Let's build it.</span></h2><p>I'm open to frontend opportunities, internships, collaborations and interesting web projects.</p><div className="heroBtns"><a className="btn primary" href={links.email}>Email me <Icon name="ArrowUpRight" size={16}/></a><a className="btn" href="/Abdul-Salam-CV.docx" download>Download CV <Icon name="Download" size={16}/></a></div><div className="contactDetails"><a href={links.email}>Abdulsalam72907@gmail.com</a><a href={links.github} target="_blank">GitHub ↗</a><a href={links.linkedin} target="_blank">LinkedIn ↗</a><span>0309-3126755</span><span>Lahore, Pakistan</span></div></motion.div></Section></main>
<footer><div className="footerTop"><div><strong>ABDUL SALAM</strong><span>Frontend Web Developer</span></div><p>Building responsive, interactive and polished digital experiences.</p></div><div className="footerLinks"><a href={links.email}>Email</a><a href={links.github} target="_blank">GitHub</a><a href={links.linkedin} target="_blank">LinkedIn</a><a href="/Abdul-Salam-CV.docx" download>Download CV</a><a href="#top">Back to top ↑</a></div><div className="footerBottom"><span>© 2026 Abdul Salam. All rights reserved.</span><span>Lahore, Pakistan</span></div></footer>
<AnimatePresence>{active&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="backdrop" onClick={()=>setActive(null)}/><motion.div className="modalBox" initial={{y:20,scale:.98}} animate={{y:0,scale:1}} exit={{y:20,scale:.98}}><button onClick={()=>setActive(null)}><Icon name="X"/></button><ImageWithFallback src={'/images/projects/'+active[2]} alt={active[0]+' screenshot'}/><div><small>{active[1]}</small><h2>{active[0]}</h2><p>{active[3]}</p><div className="tags">{active[4].map(t=><i key={t}>{t}</i>)}</div><label>HTML · CSS · JavaScript</label></div></motion.div></motion.div>}</AnimatePresence></>}
function Section({id,n,children}){return <section className="section" id={id}><div className="kicker">{n}</div>{children}</section>};function Head({title,text}){return <div className="head"><motion.h2 variants={reveal}>{title}</motion.h2><motion.p variants={reveal}>{text}</motion.p></div>};
createRoot(document.getElementById('root')).render(<App/>);
